title: Totally Cool Math Games
description: Play cool games. Most from the Ultimate Game Stash: https://rb.gy/htghms

theme: jekyll-theme-hacker

url: "https://schooluser982.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
